---

- name: Generate PHP Dockerfiles
  hosts: all
  gather_facts: false
  tags:
    - template
  tasks:
    - name: Create dist for all supported PHP versions
      ansible.builtin.import_tasks: roles/dev/main.yml

...
